git clone https://gist.github.com/0x240x23elu
git clone https://gist.github.com/ResistanceIsUseless/e46848f67706a8aa1205c9d2866bff31
git clone https://github.com/0x727/ObserverWard_0x727
git clone https://github.com/0xAwali/Blind-SSRF
git clone https://github.com/0xAwali/Virtual-Host
git clone https://github.com/1in9e/my-nuclei-templates
git clone https://github.com/5cr1pt/templates
git clone https://github.com/arielril/nuclei-templates
git clone https://github.com/ARPSyndicate/kenzer-templates
git clone https://github.com/AshiqurEmon/nuclei_templates
git clone https://github.com/AshiqurEmon/nuclei_templates.git
git clone https://github.com/BeRserKerSec/CVE-2021-26084-Nuclei-template
git clone https://github.com/bjhulst/nuclei-custom-templates
git clone https://github.com/bufferbandit/gitScanNucleiTemplate
git clone https://github.com/c0rv4x/scanfactory-nuclei-templates
git clone https://github.com/c3l3si4n/malicious_nuclei_templates
git clone https://github.com/CharanRayudu/Custom-Nuclei-Templates
git clone https://github.com/ChiaraNRTT96/BountySkill
git clone https://github.com/clarkvoss/Nuclei-Templates
git clone https://github.com/compr00t/nuclei-templates
git clone https://github.com/d3sca/Nuclei_Templates
git clone https://github.com/daffainfo/my-nuclei-templates
git clone https://github.com/danielmofer/nuclei_templates
git clone https://github.com/ekinsb/Nuclei-Templates
git clone https://github.com/emadshanab/nuclei-templates
git clone https://github.com/emadshanab/Nuclei-Templates-Collection
git clone https://github.com/esetal/nuclei-bb-templates
git clone https://github.com/ethicalhackingplayground/erebus
git clone https://github.com/ethicalhackingplayground/erebus-templates
git clone https://github.com/foulenzer/foulenzer-templates
git clone https://github.com/geeknik/nuclei-templates-1
git clone https://github.com/geeknik/the-nuclei-templates
git clone https://github.com/Harish4948/Nuclei-Templates
git clone https://github.com/im403/nuclei-temp
git clone https://github.com/javaongsan/nuclei-templates
git clone https://github.com/joanbono/nuclei-templates
git clone https://github.com/kabilan1290/templates
git clone https://github.com/lliwi/nuclei-repo-hunter
git clone https://github.com/manasmbellani/nuclei-templates
git clone https://github.com/marcositu/nuclei-custom-templates
git clone https://github.com/medbsq/ncl
git clone https://github.com/meme-lord/Custom-Nuclei-Templates
git clone https://github.com/michaelklaan/my-nuclei-templates
git clone https://github.com/michaelklaan/nuclei-templates
git clone https://github.com/Mr219/nuclei_templates
git clone https://github.com/MR-pentestGuy/nuclei-templates
git clone https://github.com/n1f2c3/mytemplates
git clone https://github.com/Nithissh0708/Custom-Nuclei-Templates
git clone https://github.com/NitinYadav00/My-Nuclei-Templates
git clone https://github.com/notnotnotveg/nuclei-custom-templates
git clone https://github.com/obreinx/nuceli-templates
git clone https://github.com/optiv/mobile-nuclei-templates
git clone https://github.com/p3n73st3r/Nuclei-Templates
git clone https://github.com/panch0r3d/nuclei-templates
git clone https://github.com/peanuth8r/Nuclei_Templates
git clone https://github.com/pikpikcu/my-nuclei-templates
git clone https://github.com/pikpikcu/nuclei-templates
git clone https://github.com/projectdiscovery/nuclei-templates
git clone https://github.com/rafaelcaria/Nuclei-Templates
git clone https://github.com/rahulkadavil/nuclei-templates
git clone https://github.com/randomstr1ng/nuclei-sap-templates
git clone https://github.com/redteambrasil/nuclei-templates
git clone https://github.com/ree4pwn/my-nuclei-templates
git clone https://github.com/R-s0n/Custom_Vuln_Scan_Templates
git clone https://github.com/sadnansakin/my-nuclei-templates
git clone https://github.com/Saimonkabir/Nuclei-Templates
git clone https://github.com/Saptak9983/Nuclei-Template
git clone https://github.com/securitytest3r/nuclei_templates_work
git clone https://github.com/sharathkramadas/k8s-nuclei-templates
git clone https://github.com/shifa123/detections
git clone https://github.com/shifa123/nuclei-templates-all
git clone https://github.com/sickwell/nuclei-templates
git clone https://github.com/smaranchand/nuclei-templates
git clone https://github.com/sobinge/nuclei-templates
git clone https://github.com/souzomain/mytemplates
git clone https://github.com/Str1am/my-nuclei-templates
git clone https://github.com/Str1am/my-nuclei-templates/tree/main/MyPoc
git clone https://github.com/sudo-jtcsec/public-nuclei-templates
git clone https://github.com/sushant-kamble/mynuclei-template
git clone https://github.com/System00-Security/backflow
git clone https://github.com/tedmdelacruz/custom-nuclei-templates
git clone https://github.com/test502git/log4j-fuzz-head-poc
git clone https://github.com/thebrnwal/Content-Injection-Nuclei-Script
git clone https://github.com/thelabda/nuclei-templates
git clone https://github.com/toramanemre/apache-solr-log4j-CVE-2021-44228
git clone https://github.com/toramanemre/log4j-rce-detect-waf-bypass
git clone https://github.com/trickest/log4j
git clone https://github.com/vysecurity/nuclei-templates-notags
git clone https://github.com/wr00t/templates
git clone https://github.com/yavolo/nuclei-templates
git clone https://github.com/z3bd/nuclei-templates
git clone https://github.com/zinminphyo0/KozinTemplates
